spring.application.name=ApiGateway

server.port=8084

# Eureka Client Configuration  by default this is true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Route 1: USER-SERVICE
spring.cloud.gateway.routes[0].id=USERSERVICE
spring.cloud.gateway.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

# Route 2: HOTEL-SERVICE
spring.cloud.gateway.routes[1].id=HOTELSERVICE
spring.cloud.gateway.routes[1].uri=lb://HOTELSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/hotels/**,/staffs/**
# OR spring.cloud.gateway.routes[1].predicates[0]=Path=/**

# Route 3: RATING-SERVICE
spring.cloud.gateway.routes[2].id=RATINGSERVICE
spring.cloud.gateway.routes[2].uri=lb://RATINGSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/ratings/**


#api configuration fro OKTA for Api  Security
spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-8z2olr1kzku12a5s.us.auth0.com/



# OAuth2 Client Registration
spring.security.oauth2.client.registration.auth0.provider=auth0
spring.security.oauth2.client.registration.auth0.client-id=tpc_tRsmnALVtbJvZF5dmBBxho
spring.security.oauth2.client.registration.auth0.client-secret=JOBMomcak5WvdvS_4NxCSbuQFWy9jJ9jb2-dwvetdTwVsWy0RkjS-FPB4M7p7svN
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.registration.auth0.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.auth0.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.auth0.client-authentication-method=client_secret_basic

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-8z2olr1kzku12a5s.us.auth0.com/